### ISSUE TITLE
2 Door Opener v10

### ISSUE THREAD

**Issue by angipp01** [REHolt/Garage-Door#6]
It was driving me crazy,  I couldn't figure out why when the door contacts connected the it would always read "partially open"  It will never say "closed".  I found a little typo with your code for Garage door 2. 

Look at line 115
attachInterrupt(digitalPinToInterrupt(Door1Status2), Status2, CHANGE);

it should be 
attachInterrupt(digitalPinToInterrupt(Door2Status2), Status2, CHANGE);

Now It will read the door contacts correctly.  
(I was hoping this was my source to issue of why I still can't get text.  Nope.  Still looking)

**Comment by REHolt** [comment]
Yea, for mine I have 2 sensors, one for open and one for closed. Anything else is "partially open". 

Sorry it's taking me so long. I was looking at the code this week, but got distracted. I am on vacation this next week and plan to try to fix it. It looks like the SMS text proplem is in the area of the door open timer. 

Hopefully I can look at it this evening when we get where we are going. I have another 4 hours of driving ahead of me.
